- src/scheduler/mod.rs
This test checks if the scheduler guards against having more than one task running on a single resource at a time.
> test: add resource guard test

- src/scheduler/mod.rs
@keyvank I think this does what is needed to accommodate your `FnOnce` change while also preserving (and fixing — there was a flaw) the desired concurrent behavior. I moved the scheduling loop out of `SchedulerRoot` and into `Scheduler`'s scheduling function. Now the lock on `SchedulerRoot` is released during the pauses — which allows the main scheduling loop to run and potentially schedule the newly-enqueued task. I think this means we can do away with the `Mutex` on the tasks in `own_tasks` (as you originally wanted) and rely on the one on `SchedulerRoot`. There might still be some picky wrinkles to iron out, but I think the general shape of this is okay now. We're gradually winding toward the goal.
> Release SchedulerRoot lock during pauses when scheduling.

- Cargo.toml
- src/scheduler/mod.rs
Changes:
1- I removed most of the lazy_static variables we had and moved them into the tests, other than the Schedulers
2- Instead of writing a big lazy_static scope containing a Scheduler for each test, we use a macro call: `new_scheduler!(...)`
3- `test_schedule_fn` now schedules tasks with random priority order, and in the end, it checks if the tasks are ran in a sorted order
4- In `test_scheduler`, instead of sleeping before throwing new set of tasks, we wait for their channels.
> feat: refactor tests

- Cargo.toml
- src/opencl/mod.rs
- src/opencl/utils.rs
Repeatedly calling `ocl::Platform::list()` is expensive when there are no OpenCL platforms. This was leading to extremely slow tests in CI, since our current workflow involves this call happening many times (at ten seconds each).
For now, a simple way to avoid that problem is to remember (in a lazy static) whether or not we receive an error (which happens in the slow case) and just return an empty list if we did previously. This assumes we won't actually receive errors when listing platforms if there are any, which is a safe assumption for now.
> Avoid repeatedly listing OpenCL platforms, if there are none.

- src/opencl/error.rs
- src/opencl/mod.rs
This PR adds support for `GPUSelector` enum for use in specifying a GPU to use (either by BusID or by position within a list of all available devices).
Similar code currently exists in [`neptune`](https://github.com/filecoin-project/neptune). Moving it here will allow `neptune` to depend on behavior here for GPU selection.
The next step will be to support similar selection in Bellman. The goal is to unify GPU device selection across all repos relying on `rust-gpu-tools`. Once that is accomplished, we can focus on eliminating problematic behavior from the unified implementation.
> Add GPUSelector.

- src/opencl/mod.rs
- src/opencl/utils.rs
Prior to this change the devices were a hash map where the key is the
brand and the value are the corresponding devices. This was an
unnecessary indirection as we only care about the devices. The devices
still contain the brand information, so you can filter a certain
brand by looping through the devices.
This commit also makes `DEVICES` only public to the crate and removes
the global public `PLATFORMS`.
These code change won't break the current upstream users bellperson and
neptune. On both the CI passes:
- https://app.circleci.com/pipelines/github/filecoin-project/bellperson/1073/workflows/8e247652-4dae-4de9-b70e-1c62994da2f8
- https://app.circleci.com/pipelines/github/filecoin-project/neptune/562/workflows/f1f9a9f2-ec30-4cb3-a0f8-ee84457f239a
> refactor: devices are now a vector

- src/opencl/mod.rs
- src/opencl/utils.rs
Remove all glob imports. This makes the code clearer. Also make `get_memory()`
private as it isn't used in `bellperson` or `neptune`.
> refactor: remove glob imports

- src/opencl/mod.rs
The last commit accidentally made the error types private.
> fix: make error types public again

- .circleci/config.yml
Clippy is run on CI, but even if there are warnings, the CI doesn't
fail. With this commit the CI fails when there are Clippy warnings.
It would now run Clippy on all the code (also benchmarks and examples).
> chore: improve Clippy on CI

- Cargo.toml
- src/opencl/error.rs
- src/opencl/mod.rs
- src/opencl/utils.rs
This PR makes the switch from `ocl` to `opencl3`. This is mostly what the first commit. On top of that there are other improvements which make sense in the light of future CUDA integration.
For easier review you might want to review this PR commit per commit (also see the commit messages for more information).
This PR also needs changes to the upstream dependants, which can be found here:
- https://github.com/filecoin-project/bellperson/pull/187
- https://github.com/filecoin-project/neptune/pull/91
> Switch from ocl to opencl3

- src/opencl/error.rs
- src/opencl/mod.rs
- src/opencl/utils.rs
The `Brand` was related to the platform. On Macs with an AMD graphics
card, it would return `Apple`. This is not really helpful, therefore
change it to `Vendor`, which will always contain the Vendor of the
graphics card.
BREAKING CHANGE: `Brand` is removed, use `Vendor` instead.
> feat: replace `Brand` with `Vendor`

- src/opencl/mod.rs
This library needs a working GPU, so it's OK to fail if there is
none. Also print out the devices that were found, this is useful
for debugging purpose as now you can see the detected devices
with running:
cargo test opencl::test::test_device_all -- --nocapture
> test: improve device test

- src/opencl/mod.rs
- src/opencl/utils.rs
There were problems identifying AMD cards correctly [1]. The reason is
that the code so far was tested with integrated AMD GPUs on Apple
devices, which report "AMD" as vendor name. Though usually the vendor
name of AMD is "Advanced Micro Devices, Inc.". Both should be supported.
As the code needed to change anyway, I decided to switch from string
identifiers to using the vendor ID, which is a numeric value. This
should lead to a more robust identification.
This commit also changes the `Display` string for AMD, it's now using
the more common "Advanced Micro Devices, Inc." instead of "AMD".
[1]: https://github.com/filecoin-project/rust-gpu-tools/issues/45
> fix: identify AMD cards correctly

- src/opencl/mod.rs
Use everything except for the raw device pointer for the `Hash` and
`PartialEq` implementation.
> fix: use more data for `Hash` and `PartialEq` implementation

- Cargo.toml
- src/opencl/mod.rs
- src/opencl/utils.rs
With the 0.4 release of `opencl` it's now possible to compile with
OpenCL 1.2 features only. This is needed for MacOS as the linking
would fail if the library contains symbols from newer OpenCL verisons.
> fix: make it linkable on MacOS

- examples/add.rs
Hello, 
I noticed there was a chance of data race happening in `add` example, because
```
dispatched number of work-groups: 8
dispatched work-group sizes: 4
```
as written [here](https://github.com/filecoin-project/rust-gpu-tools/blob/d3b36477c7d2017e2b7ea284fd91342a667835db/examples/add.rs#L41)
Following [this](https://github.com/filecoin-project/rust-gpu-tools/blob/705641f36bedff317c30f1608594ad03f082d7eb/src/opencl/mod.rs#L258-L264) comment, current [implementation](https://github.com/filecoin-project/rust-gpu-tools/blob/d3b36477c7d2017e2b7ea284fd91342a667835db/examples/add.cl#L12-L14) should invoke 32 work-items ( or threads ) and each of them should be executing same loop over 4 input elements and writing to same memory locations, which can be avoided.
This PR fixes it by launching …
> Avoid Possible Data Race in `add` example

- Cargo.toml
- README.md
- src/corecounts.rs
- src/lib.rs
For maxing out a GPU it's sometimes useful to know the number of CUDA cores.
This commit adds a mapping between graphic cards name and their number of
CUDA cores.
For non CUDA cards an appropriate number based on the compute units is chosen.
If your card isn't specified, you can add it to the list via the
`RUST_GPU_TOOLS_CUSTOM_CPU` environment variable. Example:
RUST_GPU_TOOLS_CUSTOM_GPU="GeForce RTX 2080 Ti:4352,GeForce GTX 1060:1280"
This code was originally developed as part of bellperson:
https://github.com/filecoin-project/bellperson/blob/dcf8a467a05796cf0f7fb9e170b6fc6845b42d9f/src/gpu/utils.rs#L6-L56
> feat: add core counts

- src/lib.rs
Put the information on how to add custom CUDA core counts via an
environment variable to the top level crate docs. This way it can
easily be linked to.
> docs: add information about custom core counts to crate doc

- Cargo.toml
- src/corecounts.rs
A graphics card may contain colons, so just use the last one as a
separator between the name and the number of cores.
This was reported at
https://github.com/filecoin-project/bellperson/issues/253
> fix: take only last colon of BELLMAN_CUSTOM_GPU into account

- src/cuda/mod.rs
- src/cuda/utils.rs
- src/device.rs
- src/opencl/mod.rs
- src/opencl/utils.rs
It is now possible to get the number of compute units (OpenCL) or
streaming multiprocessors (CUDA) from a `Device`.
> feat: add number of compute units to public API

- src/cuda/mod.rs
- src/opencl/mod.rs
If your project can run on both, CUDA and OpenCL, it is useful to know which version is run. To keep the noise low, add debug logging when the program is created, this should only happen less often then kernel invocations.
> feat: add logging whether CUDA or OpenCL is used

- Cargo.toml
- src/cuda/utils.rs
- src/device.rs
Prior to this change, we were using `lazy_static`. While this worked, there is a problem if the `lazy_static` `spin_no_std` features gets enabled. It then requires the types used to implement `Send`.
`once_cell` has the same requirement, which was one of the reasons not to use it. Though it makes sense to implement `Send` for the `CudaContexts`. This means that now the more ergonomic `once_cell` can be used.
Fixes #66.
> feat: switch to once_cell

- .circleci/config.yml
Using GPU workers is only needed for running the tests. Use other (way cheaper) machines for the other steps. This reduces the costs by about 7.5x (from around 1300 to 170 credits).
Also the total runtime is about half now.
> chore: redo CI
